### ISSUE TITLE
No file directory error

### ISSUE THREAD

**Issue by i701** [mahancoder/Adobe-Connect-Linux#1] opened 2021-11-12 19:04 UTC
i followed the instructions and got this error

```touch: cannot touch '/root/.config/mimeapps.list': No such file or directory```
```/usr/bin/xdg-mime: line 873: /root/.config/mimeapps.list.new: No such file or directory```

**Comment by mahancoder** [comment] 2021-11-13 07:38
This issue seems to be caused by improperly configured xdg-mime. It seems like you are installing the app as root. Either try as a normal user. Or create the not found directory:
`mkdir /root/.config`

**Comment by i701** [comment] 2021-11-13 08:15
i created the directory and app was installed but the app does not open or runs.

**Comment by mahancoder** [comment] 2021-11-13 16:14
Try
`xdg-open connectpro:https://google.com`
and give me the results

**Comment by mahancoder** [comment] 2021-11-20 12:58
Fixed in v1.0

**Closed by mahancoder** 2021-11-20 12:58 UTC
